<?php
/**
 * Created by Digital-Solution.Ru web-studio.
 * https://digital-solution.ru
 * support@digital-solution.ru
 */

namespace modules\content\models;


use framework\components\db\ActiveRecord;
use framework\core\Application;

class FeedBackAnswer extends ActiveRecord
{
    public static function tableName()
    {
        return "content_feedback_answers"; // TODO: Change the autogenerated stub
    }

    public function __construct($id_form)
    {
        parent::__construct();
       $this->id_form = $id_form;
    }
}