<?php
/**
 * Created by Digital-Solution.Ru web-studio.
 * https://digital-solution.ru
 * support@digital-solution.ru
 */

namespace modules\content\models;


use framework\components\db\ActiveRecord;
use framework\components\db\SqlBuilder;
use framework\core\Application;

class FeedBack extends ActiveRecord
{
    public static function tableName()
    {
        return "content_feedback"; // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return array_merge([
            'id' => '#',
            'name' => 'Название',
            'email_to' => 'E-Mail Получателя',
            'email_from' => 'E-Mail Отправителя',
            'use_captcha' => 'Требовать ввод кода с картинки',
            'save_results' => 'Сохранять результаты',
            'success_text' => 'Текст после отправки',
            'success_url' => 'URL перенаправления'
        ],
            parent::attributeLabels());
    }

    public function getFormField()
    {
        $field = new FeedBackField();
        $field->id_form = $this->getIdentity();

        return $field;
    }

    public function getFormFields()
    {
        return FeedBackField::findAll(['id_form' => $this->getIdentity()]);
    }

    public function getAnswers()
    {
        return $this->hasMany(FeedBackAnswer::className(), ['id_form' => $this->getIdentity()]);
    }

    public function getAnswersCount()
    {
        $sql = new SqlBuilder();
        $sql->fields('count(id)')
            ->select(FeedBackAnswer::tableName())
            ->where(['id_form' => $this->getIdentity()]);

        return $sql->column();
    }

    public function getNewAnswersCount()
    {
        $sql = new SqlBuilder();
        $sql->fields('count(id)')
            ->select(FeedBackAnswer::tableName())
            ->where([
                ['id_form' => $this->getIdentity()],
                ['unread' => 1],
            ]);

        return $sql->column();
    }
}