<?php
/**
 * Created by Digital-Solution.Ru web-studio.
 * https://digital-solution.ru
 * support@digital-solution.ru
 */

namespace modules\content\models;


use framework\components\db\ActiveRecord;
use framework\core\Application;

class Menu extends ActiveRecord
{
    public static function tableName()
    {
        return 'content_menu';
    }

    public function attributeLabels()
    {
        return array_merge([
            'id' => 'ID',
            'name' => 'Подпись',
            'url' => 'Адрес',
            'priority' => 'Приоритет',
            'id_parent' => 'Вложен',
            'access' => 'Доступ',
        ],
            parent::attributeLabels()); // TODO: Change the autogenerated stub
    }

    public static function widget()
    {
        $st = '';
        $models = static::find(['id_parent < 1'])->orderBy(['priority' => 'asc'])->all();

        if(count($models) > 0)
            foreach ($models as $model) {
                $st .= "<div class=\"menu-element\">\n"
                    ."  <a href=\"".$model->url."\">".$model->name."</a>\n"
                    ."</div>\n";
            }

        return $st;
    }
}