<?php
/**
 * Created by Digital-Solution.Ru web-studio.
 * https://digital-solution.ru
 * support@digital-solution.ru
 */

namespace modules\content\models;


use framework\models\Attachment;
use framework\core\Application;

class PageImage extends Attachment
{
    const PREFIX = 'page_';
    protected $_uploadPath = 'uploads/content/preview';

    public function getWebPath()
    {
        $webPath = parent::getWebPath(); // TODO: Change the autogenerated stub

        if($webPath == '/'.$this->_uploadPath.'/')
            return $webPath.'no-image.png';
        else
            return $webPath;
    }
}